apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/inloco.com.br_actionsrunners.yaml
- bases/inloco.com.br_actionsrunnerjobs.yaml
- bases/inloco.com.br_actionsrunnerreplicasets.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml

patches:
- path: patches/cainjection_in_actionsrunners.yaml
#+kubebuilder:scaffold:crdkustomizeresource
# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_actionsrunnerjobs.yaml
#- path: patches/cainjection_in_actionsrunnerreplicasets.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch
