
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-inloco-com-br-v1alpha1-actionsrunner
  failurePolicy: Fail
  name: vactionsrunner.kb.io
  rules:
  - apiGroups:
    - inloco.com.br
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - actionsrunners
  sideEffects: None
