# give deploy permission for cd service account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-actions-cd
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-actions-cd
  namespace: kube-actions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-actions-cd
subjects:
- kind: ServiceAccount
  name: cd-prod-continuous
  namespace: kube-actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-actions-cd
  namespace: kube-actions
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-actions-cd
  namespace: kube-actions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-actions-cd
subjects:
- kind: ServiceAccount
  name: cd-prod-continuous
