apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-actions
bases:
  - ../../config/default
resources:
  - ./configmap.yaml
generators:
  - ./secret.yaml
images:
- name: inloco/kube-actions
  newName: public.ecr.aws/incognia/kube-actions
  newTag: 65cfee1-operator
