apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-actions
resources:
- ../../config/default
- ./docker-pull.daemonset.yaml
- ./configmap.yaml
generators:
- ./secret.yaml
images:
- name: incognia/kube-actions
  newName: public.ecr.aws/incognia/kube-actions
  newTag: cc60cb8-operator
- name: incognia/kube-actions-operator
  newName: public.ecr.aws/incognia/kube-actions
  newTag: cc60cb8-operator
- name: incognia/kube-actions-runner
  newName: public.ecr.aws/incognia/kube-actions
  newTag: cc60cb8-runner
- name: incognia/kube-actions-dind
  newName: public.ecr.aws/incognia/kube-actions
  newTag: cc60cb8-dind
