version: 2
updates:
  - package-ecosystem: docker
    directory: /dind
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /operator
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /runner
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /dind
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /operator
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /runner
    schedule:
      interval: daily
