apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-actions
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - persistentvolumeclaims
      - secrets
    verbs:
      - create
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
  - apiGroups:
      - inloco.com.br
    resources:
      - actionsrunners
    verbs:
      - '*'
