creation_rules:
  - path_regex: operator/k8s/production/
    kms: arn:aws:kms:us-east-1:779099367007:alias/kube-actions
    encrypted_regex: ^(data|stringData)$
  - path_regex: operator/k8s/development/
    kms: arn:aws:kms:us-east-1:779099367007:alias/kube-actions
    encrypted_regex: ^(data|stringData)$
