# permissions for end users to edit actionsrunnerreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actionsrunnerreplicaset-editor-role
rules:
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunnerreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunnerreplicasets/status
  verbs:
  - get
