# permissions for end users to view actionsrunnerjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actionsrunnerjob-viewer-role
rules:
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunnerjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunnerjobs/status
  verbs:
  - get
