# permissions for end users to view actionsrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actionsrunner-viewer-role
rules:
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunners/status
  verbs:
  - get
