# permissions for end users to edit actionsrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actionsrunner-editor-role
rules:
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunners/status
  verbs:
  - get
