
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunner
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunner/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunnerjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunnerjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunnerreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunnerreplicasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inloco.com.br
  resources:
  - actionsrunners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - poddisruptionbudgets/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
