apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-actions
  name: binfmt-misc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-actions
      app.kubernetes.io/component: binfmt-misc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-actions
        app.kubernetes.io/component: binfmt-misc
    spec:
      initContainers:
        - name: register
          image: multiarch/qemu-user-static
          args:
            - --reset
            - --persistent
            - 'yes'
          resources:
            requests:
              cpu: 2m
              memory: 8Mi
          securityContext:
            privileged: true
      containers:
        - name: pause
          image: k8s.gcr.io/pause
          resources:
            limits:
              cpu: 2m
              memory: 8Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
