#!/bin/sh
set -ex

# stop dockerd after connection from runner at end of job
{
    nc -l -p 2378 > /dev/null
    kill -s INT $(pidof dockerd || printf ${PPID})
} &


# create iptables rules and use socat proxy to make containers reachable by their IPs
/sbin/dind &

set -- ${DOCKERD_ENTRYPOINT_ARGS} "${@}"
. /usr/local/bin/dockerd-entrypoint.sh "${@}"
