#!/bin/sh
set -ex

# stop dockerd after connection from runner at end of job
{
    nc -l -p 2378 > /dev/null
    kill -s INT $(pidof dockerd || printf ${PPID})
} &


# create iptables rules to make port-exporting containers reachable by any IP
/sbin/docker-iptables-glue &

set -- ${DOCKERD_ENTRYPOINT_ARGS} "${@}"
. /usr/local/bin/dockerd-entrypoint.sh "${@}"
