apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: kube-actions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - --max-concurrent-reconciles=1000
        - --metrics-bind-address=:9102
        image: inloco/kube-actions
        name: manager
        envFrom:
        - configMapRef:
            name: controller-manager
        - secretRef:
            name: controller-manager
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 1500m
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
