apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: kube-actions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --max-concurrent-reconciles=1000
        - --metrics-bind-address=:9102
        image: inloco/kube-actions:to-be-replaced
        name: manager
        envFrom:
        - configMapRef:
            name: controller-manager
        - secretRef:
            name: controller-manager
        env:
        - name: KUBEACTIONS_RUNNER_IMAGE_NAME
          value: 779099367007.dkr.ecr.us-east-1.amazonaws.com/incognia/kube-actions
        - name: KUBEACTIONS_DIND_IMAGE_NAME
          value: 779099367007.dkr.ecr.us-east-1.amazonaws.com/incognia/kube-actions
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
