#!/bin/bash
set -ex

git config --global user.name github-actions[bot]
git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

if [ -z "${AWS_REGION}" ]
then
	export AWS_REGION=$(curl -Lf http://instance-data.ec2.internal/latest/meta-data/placement/region)
fi

if RESP=$(aws sts get-caller-identity 2> /dev/null)
then
	export AWS_ACCOUNT=$(printf "${RESP}" | jq -r '.Account')
	export AWS_CALLER_ARN=$(printf "${RESP}" | jq -r '.Arn')
	export AWS_CALLER_ID=$(printf "${RESP}" | jq -r '.UserId')
fi

if [ ! -z "${DOCKER_HOST}" ]
then
	PROT=$(printf ${DOCKER_HOST} | sed -En 's|^(.+)://.+$|\1|p')
	ADDR=$(printf ${DOCKER_HOST} | sed -En 's|^.+://(.+)$|\1|p')
	ARGS=

	case $PROT in
	tcp)
		ADDR=$(printf ${ADDR} | sed 's/:/ /')
		;;

	unix)
		ARGS='-f'
		;;

	*)
		echo "${PROT} protocol not supported" >&2
		exit 1
		;;
	esac

	until $(nc ${ARGS} ${ADDR} < /dev/null)
	do
		if [ $((__++)) -eq 15 ]
		then
			echo "unable to connect to ${ADDR}" >&2
			exit 1
		fi

		sleep 1
	done

	function pre-stop {
		nc localhost 2378 < /dev/null
	}
	trap pre-stop EXIT INT QUIT TERM

	export DOCKER_CONFIG=${DOCKER_CONFIG:-${HOME}/.docker}
	if [ ! -d ${DOCKER_CONFIG} ]
	then
		mkdir -p ${DOCKER_CONFIG}
	fi

	CONF=${DOCKER_CONFIG}/config.json
	if [ ! -f ${CONF} ]
	then
		echo '{}' > ${CONF}
	fi

	if [ ! -z "${DOCKER_AUTHS}" ]
	then
		envsubst <<< $(jq --argjson _ "${DOCKER_AUTHS}" '.auths |= . + $ARGS.named["_"]' ${CONF} || cat ${CONF}) > ${CONF}
	fi

	if [ ! -z "${DOCKER_CREDENTIAL_HELPERS}" ]
	then
		envsubst <<< $(jq --argjson _ "${DOCKER_CREDENTIAL_HELPERS}" '.credHelpers |= . + $ARGS.named["_"]' ${CONF} || cat ${CONF}) > ${CONF}
	fi

	if [ ! -z "${DOCKER_PLUGINS}" ]
	then
		envsubst <<< $(jq --argjson _ "${DOCKER_PLUGINS}" '.plugins |= . + $ARGS.named["_"]' ${CONF} || cat ${CONF}) > ${CONF}
	fi
fi

sudo update-ca-certificates

. /opt/actions-runner/run.sh --once
