name: Continuous
on:
  - push
  - workflow_dispatch
jobs:
  build:
    name: Build
    strategy:
      matrix:
        component:
          - dind
          - operator
          - runner
    runs-on:
      - self-hosted
      - ci
      - linux
      - amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: make -C ${{ matrix.component }} continuous-build
      - name: Save docker image
        uses: inloco/actions-cache@HEAD
        id: cache-image
        with:
          path: ${{ matrix.component }}/image.tar
          key: ${{ runner.os }}-image-${{ matrix.component }}-${{ github.sha }}

  push:
    name: Push
    needs: build
    strategy:
      matrix:
        component:
          - dind
          - operator
          - runner
    runs-on:
      - self-hosted
      - cd-prod-continuous
      - linux
      - amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download docker image
        uses: inloco/actions-cache@HEAD
        id: cache-image
        with:
          path: ${{ matrix.component }}/image.tar
          key: ${{ runner.os }}-image-${{ matrix.component }}-${{ github.sha }}
      - name: Make
        run: make -C ${{ matrix.component }} continuous-push
