name: Continuous
on: push
jobs:
  build:
    name: Build
    strategy:
      matrix:
        component:
          - dind
          - operator
          - runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: make -C ${{ matrix.component }} continuous-build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.component }}
          path: ${{ matrix.component }}/image.tar
  push:
    name: Push
    needs: build
    strategy:
      matrix:
        component:
          - dind
          - operator
          - runner
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.component }}
          path: ${{ matrix.component }}
      - name: Make
        run: make -C ${{ matrix.component }} continuous-push
