name: Continuous
on:
  - push
  - workflow_dispatch
jobs:
  build:
    name: Build
    strategy:
      matrix:
        component:
          - dind
          - operator
          - runner
    runs-on:
      - self-hosted
      - ci
      - linux
      - amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: make -C ${{ matrix.component }} continuous-build
      - name: Save docker image
        uses: inloco/actions-cache@HEAD
        id: cache-image
        with:
          path: ${{ matrix.component }}/image.tar
          key: ${{ runner.os }}-image-${{ matrix.component }}-${{ github.sha }}

  push:
    name: Push
    needs: build
    strategy:
      matrix:
        component:
          - dind
          - operator
          - runner
    runs-on:
      - self-hosted
      - cd-prod-continuous
      - linux
      - amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download docker image
        uses: inloco/actions-cache@HEAD
        id: cache-image
        with:
          path: ${{ matrix.component }}/image.tar
          key: ${{ runner.os }}-image-${{ matrix.component }}-${{ github.sha }}
      - name: Make
        run: make -C ${{ matrix.component }} continuous-push

  deploy:
    name: Deploy
    needs: push
    if: github.ref == 'refs/heads/master'
    runs-on:
      - self-hosted
      - cd-prod-continuous
      - linux
      - amd64
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install controller-gen
        run: go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest
      - name: Install sops
        run: go install go.mozilla.org/sops/v3/cmd/sops@latest
      - name: Download Kubernetes tools
        run: |
          curl -LOs "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -Ls "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.3.0/kustomize_v4.3.0_linux_amd64.tar.gz" | tar -xzf - > kustomize
          chmod +x kubectl kustomize
          sudo mv kubectl /usr/bin/kubectl
          sudo mv kustomize /usr/local/bin/kustomize
      - name: Install Kustomize SOPS Plugin
        run: |
          PLACEMENT=${XDG_CONFIG_HOME:-$HOME/.config}/kustomize/plugin/inloco.com.br/v1/sops
          mkdir -p $PLACEMENT
          curl -Lo $PLACEMENT/SOPS https://github.com/inloco/sops-kustomize-generator-plugin/releases/download/v1.1.1/plugin-linux-amd64
          chmod +x $PLACEMENT/SOPS
      - name: Make
        run: make -C operator deploy/production
